# Generated by Django 4.2.4 on 2023-08-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_budget', models.CharField(choices=[('AC', 'Année courante'), ('PR', 'Projets'), ('FE', 'Financements exceptionnels')], max_length=2)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='emprunt.enseignant')),
                ('possesseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='emprunt.enseignant')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matériels', to='emprunt.enseignant')),
            ],
        ),
        migrations.RemoveField(
            model_name='matériel',
            name='acheteur',
        ),
        migrations.RemoveField(
            model_name='matériel',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='matériel',
            name='possesseur',
        ),
        migrations.RemoveField(
            model_name='matériel',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='matériel',
            name='salle',
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.IntegerField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.AddField(
            model_name='materiel',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matériels', to='emprunt.salle'),
        ),
        migrations.AlterField(
            model_name='accessoire',
            name='matériel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='emprunt.materiel'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='matériel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprunt.materiel'),
        ),
        migrations.DeleteModel(
            name='Matériel',
        ),
    ]
