# Generated by Django 4.2.4 on 2023-08-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0002_materiel_remove_matériel_acheteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_budget', models.CharField(choices=[('AC', 'Année courante'), ('PR', 'Projets'), ('FE', 'Financements exceptionnels')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='type_budget',
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='materiel',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emprunt.budget'),
        ),
    ]
